language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - SCRIPT=platformioSingle EXAMPLE_NAME=TriggerEvent EXAMPLE_FOLDER=/ BOARDTYPE=ESP8266 BOARD=d1_mini
    - SCRIPT=platformioSingle EXAMPLE_NAME=TriggerEvent EXAMPLE_FOLDER=/ BOARDTYPE=101 BOARD=mkr1000USB

install:
    - pip install -U platformio
    #
    # Libraries from PlatformIO Library Registry:
    #
    # http://platformio.org/lib/show/64/ArduinoJson
    - platformio lib -g install 64
    # http://platformio.org/lib/show/299/WiFi101
    - platformio lib -g install 299

script: scripts/travis/$SCRIPT.sh
